function [macroRNs, macroANs] = LoadMacroBackup(pathFolderCTD)
%
% [macroRNs, macroANs] = LoadMacroBackup(pathFolderCTD)
%
% Checks existence of "macroCells.mat" file (generated by CTD) and, if found, load "macroANs" and "macroRNs".
%
% version 1.0
% Boris Guirao

%% Code %%

macroCellsBackup = [pathFolderCTD filesep 'macroCells.mat'];

if exist(macroCellsBackup,'file')
    
    fprintf('Loading ANs of macrochaetes...');
    load(macroCellsBackup,'macroRNs','macroANs');
    fprintf('Done\n');
else
    fprintf('No macrochaetae file found.\n');
    macroRNs = [];
    macroANs = [];
end


%% History %%

% 30/11/2017: creation